### ISSUE TITLE
Review and test the code to gauge scale of the work needed

### ISSUE THREAD

**Issue by Danyc0** [abersailbot/dewi-boatd-driver#1]
Review and test the Dewi boatd Driver code to gauge scale of the work needed for a semi-functioning boat

**Comment by kragniz** [comment]
This looks almost identical to kitty code, apart from the wind sensor reading. I think this mostly worked on kitty, so it should be okay here with some testing.

**Comment by kragniz** [comment]
You'll also want a udev rule to set up the `/dev/arduino` device: https://github.com/abersailbot/kitty-provisioner/blob/master/etc/52-arduino.rules
